// Code generated by goctl. DO NOT EDIT!
// Source: logic.proto

//go:generate mockgen -destination ./logicCli_mock.go -package logiccli -source $GOFILE

package logiccli

import (
	"context"

	"github.com/1211ciel/fall/im/logic/logicpb"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ConnectReq   = logicpb.ConnectReq
	ConnectReply = logicpb.ConnectReply
	PushMsg      = logicpb.PushMsg

	LogicCli interface {
		//  提供给comet 用户连接时进行鉴权
		Connect(ctx context.Context, in *ConnectReq) (*ConnectReply, error)
	}

	defaultLogicCli struct {
		cli zrpc.Client
	}
)

func NewLogicCli(cli zrpc.Client) LogicCli {
	return &defaultLogicCli{
		cli: cli,
	}
}

//  提供给comet 用户连接时进行鉴权
func (m *defaultLogicCli) Connect(ctx context.Context, in *ConnectReq) (*ConnectReply, error) {
	client := logicpb.NewLogicCliClient(m.cli.Conn())
	return client.Connect(ctx, in)
}
