// Code generated by goctl. DO NOT EDIT!
// Source: comet.proto

package server

import (
	"context"

	"github.com/1211ciel/fall/im/comet/cometpb"
	"github.com/1211ciel/fall/im/comet/internal/logic"
	"github.com/1211ciel/fall/im/comet/internal/svc"
)

type CometCliServer struct {
	svcCtx *svc.ServiceContext
}

func NewCometCliServer(svcCtx *svc.ServiceContext) *CometCliServer {
	return &CometCliServer{
		svcCtx: svcCtx,
	}
}

func (s *CometCliServer) PushMsg(ctx context.Context, in *cometpb.PushReq) (*cometpb.CometEmpty, error) {
	l := logic.NewPushMsgLogic(ctx, s.svcCtx)
	return l.PushMsg(in)
}
