// Code generated by goctl. DO NOT EDIT!
// Source: logic.proto

package server

import (
	"context"

	"github.com/1211ciel/fall/im/logic/internal/logic"
	"github.com/1211ciel/fall/im/logic/internal/svc"
	"github.com/1211ciel/fall/im/logic/logicpb"
)

type LogicCliServer struct {
	svcCtx *svc.ServiceContext
}

func NewLogicCliServer(svcCtx *svc.ServiceContext) *LogicCliServer {
	return &LogicCliServer{
		svcCtx: svcCtx,
	}
}

//  提供给comet 用户连接时进行鉴权
func (s *LogicCliServer) Connect(ctx context.Context, in *logicpb.ConnectReq) (*logicpb.ConnectReply, error) {
	l := logic.NewConnectLogic(ctx, s.svcCtx)
	return l.Connect(in)
}
