// Code generated by goctl. DO NOT EDIT!
// Source: comet.proto

//go:generate mockgen -destination ./cometCli_mock.go -package cometcli -source $GOFILE

package cometcli

import (
	"context"

	"github.com/1211ciel/fall/im/comet/cometpb"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	PushReq    = cometpb.PushReq
	CometEmpty = cometpb.CometEmpty

	CometCli interface {
		PushMsg(ctx context.Context, in *PushReq) (*CometEmpty, error)
	}

	defaultCometCli struct {
		cli zrpc.Client
	}
)

func NewCometCli(cli zrpc.Client) CometCli {
	return &defaultCometCli{
		cli: cli,
	}
}

func (m *defaultCometCli) PushMsg(ctx context.Context, in *PushReq) (*CometEmpty, error) {
	client := cometpb.NewCometCliClient(m.cli.Conn())
	return client.PushMsg(ctx, in)
}
