// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/1211ciel/fall/test/go-zero/77/gateway/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GatewayHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
}
