// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type RegistereReq struct {
	Name string `form:"name"`
	Pwd  string `form:"pwd"`
}

type RegisterResp struct {
	Ok bool `json:"ok"`
}
