// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"github.com/1211ciel/fall/test/go-zero/78/service/user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request      = user.Request
	Response     = user.Response
	RegisterReq  = user.RegisterReq
	RegisterResp = user.RegisterResp

	User interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
		Register(ctx context.Context, in *RegisterReq) (*RegisterResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Ping(ctx, in)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in)
}
