// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/1211ciel/fall/test/go-zero/78/gateway/internal/handler/user"
	"github.com/1211ciel/fall/test/go-zero/78/gateway/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: user.GatewayHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: user.TestHandler(serverCtx),
			},
		},
	)
}
